# Generated by Django 4.2 on 2023-05-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0004_alter_imagelist_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagelist",
            name="data_url",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
