# Generated by Django 4.2 on 2023-05-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0007_alter_imagelist_data_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagelist",
            name="data_url",
        ),
    ]
