# Generated by Django 4.2 on 2023-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_imagelist_delete_multipleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagelist",
            name="images",
            field=models.FileField(upload_to=""),
        ),
    ]
