# Generated by Django 4.2 on 2023-05-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_imagelist_data_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagelist",
            name="data_url",
            field=models.JSONField(null=True),
        ),
    ]
